### ISSUE TITLE
Recommended Pre-installs

### ISSUE THREAD

**Issue by programbo** [campjs/campjs-next#41]
I've put out a call on Twitter to anyone presenting at CampJS for global modules, clone-able starter projects, or cheat sheets that will help people participate faster without thrashing the WiFi.

Also, did we host any offline docs or APIs on the intranet last year?

**Comment by johnlombardo-dev** [comment]
@Bondifrench I tweeted at your Github name which does nothing at all.

**Comment by Bondifrench** [comment]
Sorry @programbo as I saw your message on mobile, didn't see your first message.
https://github.com/cazala/synaptic
https://github.com/cazala/synaptic-workshop
Are the two resources I would be using most. Thx

**Comment by johnlombardo-dev** [comment]
Thanks a lot, @Bondifrench. It will be cool to get started with ANN and ML without learning Python.

**Comment by garrows** [comment]
@programbo can you add firechat to your list? https://www.opengarden.com/firechat.html

**Comment by AnnaGerber** [comment]
From Josh Wulf:

Participants in the Magikcraft workshop need to have a Minecraft client installed.

If you don't already have Minecraft installed:

1. Download the Magikcraft client from client.magikcraft.io.
2. Enter your Minecraft user credentials (if you don't have a Minecraft account, purchase a Minecraft account gift card from JB HiFi / Coles / 711 for $25, then redeem it at Minecraft.net).
3. Click on "Play Magikcraft!"
4. Verify that you can connect to the Magikcraft server.

You need to perform steps 3 and 4 to make sure you have downloaded all the game files.

If you already have a Minecraft client, then you need to create a profile for 1.11.2 and connect to the server at play.magikcraft.io.  This ensures that you have the game files that you will need for the workshop.

If you run into any problems, then hit up Josh Wulf: @sitapati on twitter | josh@magikcraft.io email | 0431929675 | slack.magikcraft.io.

GitHub and NPM prior art:

GitHub starter template: 
https://github.com/Magikcraft/magikcraft-lore-_template

You'll want to grab the magikcraft.io package from npm:
npm i magikcraft.io

Might want to look at these:
https://github.com/Magikcraft/product-board/issues/8
https://github.com/Magikcraft/product-board/issues/6

And take a look at these:
https://github.com/jwulf/magikcraft-lore-ui-bar
https://github.com/jwulf/magikcraft-minigame-platforms

Take a look at the Bukkit Documentation. This is the underlying API for the Minecraft server used by Magikcraft:
https://bukkit.magikcraft.io

**Comment by AnnaGerber** [comment]
From Christopher Biggs:
Okay, things to install if you want to get all IOTish in Node.   

First install a recent version of nodejs.  Use the official nodejs tarballs because if you have a linux box the packaged node builds are ancient.

Second, install these OS packages

    mosquitto
    mosquitto-clients
    
Then, all the below are NPM modules, install the musts, consider the shoulds

Must have
    homebridge  homebridge-mqtt-sensor homebridge-mqttswitch  node-red   node-red-contrib-gpio node-red-node-serialport

Should have:
homebridge-blynk homebridge-camera-ffmpeg homebridge-camera-motion homebridge-contactsensor homebridge-daylight homebridge-hue homebridge-info homebridge-ip-camera homebridge-milight homebridge-mqtt-contactsensor homebridge-mqtt-humidity homebridge-mqttlightbulb homebridge-mqtt-temperature homebridge-neopixel homebridge-panasonictv homebridge-people homebridge-weather node-red-admin node-red-contrib-blynk-websockets

**Comment by AnnaGerber** [comment]
From Julie Grundy: 
ARIA Authoring Best Practices: https://www.w3.org/TR/wai-aria-practices/
Accessibility Dev Tools for Chrome: https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en
A11y Project: http://a11yproject.com/
And some resources I frequently recommend, so they might come up even though I'm not addressing them specifically:

WebAIM's plain English WCAG checklist: http://webaim.org/standards/wcag/checklist
NVDA (free screenreader for Windows, likely a large download although I haven't checked in a while): https://www.nvaccess.org/
chrome.google.com
Accessibility Developer Tools
Accessibility audit and element properties.
 
 a11yproject.com
The A11Y Project
A community-driven effort to make web accessibility easier.
 
 nvaccess.org
NV Access
Empowering lives through non-visual access to technology

**Comment by AnnaGerber** [comment]
From Joshua Paling: git, and the npm package ‘prettier’

From Brad Barrow: https://github.com/airbnb/react-sketchapp

**Comment by AnnaGerber** [comment]
From Tommy Williams
NPM packages:

phonegap -- CLI (global npm install) -- https://www.npmjs.com/package/phonegap
cordova -- CLI (global npm install) -- https://www.npmjs.com/package/cordova
ios-sim -- tool to help launching the iOS Simulator from the CLI -- https://www.npmjs.com/package/ios-sim
ios-deploy -- tool to help launching iOS apps on an actual device -- https://www.npmjs.com/package/ios-deploy

phonegap-template-vue-f7-split-panel - Starter template used by phonegap CLI -- https://www.npmjs.com/package/phonegap-template-vue-f7-split-panel


DOCS:

https://cordova.apache.org/docs/en/latest/

http://docs.phonegap.com/getting-started/2-install-mobile-app/

and maybe http://docs.phonegap.com/

**Comment by johnlombardo-dev** [comment]
# Install these to make your CampJS life better...

### CLI version of the CampJS Website
```
npm i -g campjs && campjs
```

### Git
Installation instructions: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

### npmrc
> Switch between different .npmrc files with ease and grace.
```
npm install -g npmrc
```

### FireChat
> A free messaging app for public and private communications that works even without Internet access or cellular data.

Download for [iOS](https://itunes.apple.com/app/id719829352?mt=8&&referrer=click%3De70bf721-a2db-4fba-b41e-246a94b1ae58) and [Android](https://play.google.com/store/apps/details?id=com.opengarden.firechat&referrer=utm_source%3Dfirechat.opengarden.com%26utm_medium%3Dweb%26utm_campaign%3Dbutton) and join the #campjs room.

### Patchwork
> A decentralized messaging and sharing app built on top of Secure Scuttlebutt (SSB).

https://github.com/ssbc/patchwork

### Live Server
```
npm install -g live-server
```

### DevDocs Offline Documentation
1. Enable docs for your areas of interest: http://devdocs.io/, then
2. Install docs for offline use: http://devdocs.io/offline

# Material and preinstalls for sessions

### Elm Workshop
Preinstall: https://guide.elm-lang.org/install.html

### Workshop: Beginner’s Guide to DataViz with ThreeJS
https://robisateam.github.io/courses/threejs-course/

### Workshop: Beginner’s Guide to DataViz with D3
https://robisateam.github.io/courses/d3-course/

### Jest for API servers
Clone: https://github.com/bguiz/jest-property-testing-demo

### Magikcraft - Modding Minecraft with JavaScript
Instructions: https://github.com/campjs/campjs-next/issues/41#issuecomment-319540184

### Javascript Rules my Life
Instructions: https://github.com/campjs/campjs-next/issues/41#issuecomment-319540258

### Inclusive Javascript
Instructions: https://github.com/campjs/campjs-next/issues/41#issuecomment-319541266

### It’s Been Too Long Since You Last Looked At PhoneGap
Instructions: https://github.com/campjs/campjs-next/issues/41#issuecomment-319541924

### Do you want to build a robot? ❄️ 🎵 🤖
Instructions: https://github.com/campjs/campjs-next/issues/41#issuecomment-319552020

### luddite.js
Starter project & Cheatsheets: https://github.com/campjs/campjs-next/issues/41#issuecomment-319567947

### Engineering Experiences: Coding for design at scale
Clone and install: https://github.com/airbnb/react-sketchapp

### Copy-paste-pray? No way!
```
npm i -g prettier
```

### Machine Learning and Javascript
Discussion: https://github.com/cazala/synaptic
Clone: https://github.com/cazala/synaptic-workshop
More: https://github.com/campjs/campjs-next/issues/41#issuecomment-319550043

### Mad science with Electron
```
npm install -g electron
```

### WebAssembly 101
Primer: https://hacks.mozilla.org/2017/02/a-cartoon-intro-to-webassembly/
Installation: http://webassembly.org/getting-started/developers-guide/

**Comment by AnnaGerber** [comment]
From Bondi French:
Here are a few additional Libraries for Machine-Learning in Javascript:
Weblas https://www.npmjs.com/package/weblas

ndarray https://www.npmjs.com/package/ndarray with docs: https://github.com/scijs/scijs-ndarray-for-matlab-users
ndarray-ops https://www.npmjs.com/package/ndarray-ops
ndarray-pack https://www.npmjs.com/package/ndarray-pack
ndarray-fill https://www.npmjs.com/package/ndarray-fill
zeros https://www.npmjs.com/package/zeros

Tensorfire https://www.npmjs.com/package/tensorfire 

mljs https://www.npmjs.com/package/ml webpage https://github.com/mljs/ml

gpu.js https://github.com/gpujs/gpu.js webpage: http://gpu.rocks/

https://github.com/cazala/synaptic-workshop, there is no npm package so need to clone the github repo

**Comment by AnnaGerber** [comment]
Do you want to build a robot?

Examples in this talk will use a Raspberry Pi. If you want to experiment, your Raspberry Pi will need Raspbian, a recent version of node, and serialport, johnny-five and raspi-io installed from npm

Instructions here:
https://github.com/nebrius/raspi-io/wiki/Getting-a-Raspberry-Pi-ready-for-NodeBots

**Comment by AnnaGerber** [comment]
From Rob Kerr and Isabell Kiral-Kornek

https://robisateam.github.io/courses/d3-course/
https://robisateam.github.io/courses/threejs-course/

Also docs and examples from https://threejs.org/ and https://d3js.org/

**Comment by AnnaGerber** [comment]
From Mikey Williams

- starter project repositories on GitHub
  - https://github.com/dominictarr/pull-stream-examples
  - https://github.com/pull-stream/pull-stream-workshop
- Cheatsheets or API reference material
  - https://pull-stream.github.io
  - https://github.com/hyperhype/hyperscript
  - https://github.com/Raynos/continuable
  - https://github.com/Raynos/observ
  - https://github.com/depject/depject

**Comment by luke-john** [comment]
Starter Kits for anyone wanting to try out the `glamorous` css-in-js framework I'll be talking about.

* Create React App with `glamorous`, `glamor`, `jest-glamor-react` and `polished`
  * https://github.com/luke-john/campjs-glamorous-typescript **with typescript** 
  * https://github.com/luke-john/campjs-glamorous

**Comment by KoryNunn** [comment]
Mine just needs node 6 or above, and the ability to connect to a wifi hotspot/router.

**Comment by dannyshaw** [comment]
Offline documentation readers and pre-downloading relevant docsets:

Mac:
https://kapeli.com/dash

Linux/Windows/Mac:
https://zealdocs.org/

**Comment by AnnaGerber** [comment]
From Phil Nash:
-   [Dexie](http://dexie.org/)
-   [PouchDB](https://pouchdb.com/)
-   [idb](https://github.com/jakearchibald/idb)
-   [localForage](https://github.com/localForage/localForage)
-   [idb-keyval](https://github.com/jakearchibald/idb-keyval)

**Comment by garrows** [comment]
Thanks again for putting this together.
